server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:/mall_tiny?useUnicode=true&characterEncoding=utf-8&timeServerZone=Asia/Shanghai
    username: root
    password: 116924
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:dao/*.xml

security:
  ignored:
    urls:
      - /admin/login
      - /swagger-ui/
      - /swagger-ui/index.html
      - /swagger-resources/**
      - /**/*.js
      - /**/*.html
      - /**/*.css
      - /**/*.png
      - /**/v2/api-docs
      - /favicon.ico

jwt:
  expiration: 64800 #24*3600 S
  secret: mySecret
  tokenHeader: Authorization
  tokenHead: Bearer

