server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:/mall_tiny?useUnicode=true&characterEncoding=utf-8&timeServerZone=Asia/Shanghai
    username: root
    password: 116924
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:dao/*.xml
