server:
  port: 8085


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimeZone=Asia/Shanghai
    username: root
    password: 116924
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml  #TODO 这里classpath*不能写classpath,why?
  configuration:
    map-underscore-to-camel-case: true

secure:
  ignored:
    urls:
      - /swagger/
      - /swagger-ui/
      - /admin/**
      - /**/*.html
      - /**/*.css
      - /**/*.js
      - /swagger-resources/**
      - /v2/api-docs

jwt:
  tokenHeader: Authorization
  tokenHead: Bearer
  secret: mySecret
  expiration: 86400 #24*3600S

test:
  id: 1224
