server:
  port: 8087


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimeZone=Asia/Shanghai
    username: root
    password: 116924
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
    database: 0
    passwrod:
    timeout: 1000ms
  elasticsearch:
    uris: localhost:9200
  data:
    elasticsearch:
      repositories:
        enabled: true
    mongodb:
      host: localhost
      port: 27017
      database: mall-port2
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /mall_tiny
    username: zzy
    password: 116924
    publisher-returns: true
    publisher-confirm-type: correlated
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

minio:
  endPoint: http://localhost:9000 #minio的服务端口
  bucketName: mall
  accessKey: minioadmin
  secretKey: minioadmin


mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml  #TODO 这里classpath*不能写classpath,why?
  configuration:
    map-underscore-to-camel-case: true

secure:
  ignored:
    urls:
      - /swagger/
      - /swagger-ui/
      - /admin/**
      - /**/*.html
      - /**/*.css
      - /**/*.js
      - /swagger-resources/**
      - /v2/api-docs

jwt:
  tokenHeader: Authorization
  tokenHead: Bearer
  secret: mySecret
  expiration: 86400 #24*3600S

redis:
  key:
    prefix:
      authCode: "portal:member:"
    expire:
      authCode: 120

test:
  id: 1224
