server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&encoding=utf-8&serverTimeZone=Asia/Shanghai
    username: root
    password: 116924
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    password:
    database: 0
    port: 6379
    timeout: 1000ms


mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath:com/**/mapper/*.xml

jwt:
  expiration: 86400 # 24*60*60 S
  secret: mySecret
  tokenHeader: Authorization
  tokenHead: Bearer

secure:
  ignored:
    urls:
      - /admin/**

springfox:
  documentation:
    open-api:
      enabled: false


